name: Build Zenith-Linux ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build ISO in Fedora Container
        run: |
          # We run the Fedora 40 container in privileged mode to allow loop device mounting
          docker run --privileged -v $(pwd):/build registry.fedoraproject.org/fedora:40 \
          /bin/bash -c "cd /build && chmod +x build.sh && ./build.sh"

      - name: Upload Zenith ISO
        uses: actions/upload-artifact@v4
        with:
          name: Zenith-Linux-Alpha-ISO
          # livemedia-creator puts the final ISO in the 'output' folder we defined in build.sh
          path: "output/images/boot.iso"
          retention-days: 5