name: Build Zenith-Linux ISO
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build ISO in Fedora Container
        run: |
          docker run --privileged -v $(pwd):/build registry.fedoraproject.org/fedora:40           /bin/bash -c "cd /build && chmod +x build.sh && ./build.sh"

      - name: Upload Zenith ISO
        uses: actions/upload-artifact@v4
        with:
          name: Zenith-Linux-Alpha-ISO
          path: "*.iso"
          retention-days: 5
